name: CI

on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      plugins: ${{ steps.packages.outputs.paths }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dtinth/setup-github-actions-caching-for-turbo@cc723b4600e40a6b8815b65701d8614b91e2669e # v1
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install
      - id: files
        uses: imhoffd/get-changed-files@4064453b1b00f8f8d17f1493c90fbe1f9c40daff # v2
        with:
          format: json
      - id: packages
        uses: ./.github/actions/changed-packages
        with:
          files: ${{ steps.files.outputs.all }}
  validate:
    runs-on: macos-14
    timeout-minutes: 30
    needs:
      - setup
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dtinth/setup-github-actions-caching-for-turbo@cc723b4600e40a6b8815b65701d8614b91e2669e # v1
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install
      - run: yarn run validate
  verify-ios:
    runs-on: macos-14
    if: needs.setup.outputs.plugins != '[]'
    timeout-minutes: 30
    needs:
      - setup
      - validate
    strategy:
      matrix:
        xcode:
          - /Applications/Xcode_14.2.app
        plugin: ${{ fromJson(needs.setup.outputs.plugins) }}
    steps:
      - run: sudo xcode-select --switch ${{ matrix.xcode }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install
      - run: yarn run verify:ios
        working-directory: ${{ matrix.plugin }}
  verify-android:
    runs-on: ubuntu-latest
    if: needs.setup.outputs.plugins != '[]'
    timeout-minutes: 30
    needs:
      - setup
      - validate
    strategy:
      matrix:
        plugin: ${{ fromJson(needs.setup.outputs.plugins) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install
      - run: yarn run verify:android
        working-directory: ${{ matrix.plugin }}
  verify-web:
    runs-on: ubuntu-latest
    if: needs.setup.outputs.plugins != '[]'
    timeout-minutes: 30
    needs:
      - setup
      - validate
    strategy:
      matrix:
        plugin: ${{ fromJson(needs.setup.outputs.plugins) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .tool-versions
          cache: yarn
      - run: yarn install
      - run: yarn run verify:web
        working-directory: ${{ matrix.plugin }}
# deploy:
#   runs-on: macos-latest
#   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#   timeout-minutes: 30
#   needs:
#     - setup
#     - lint
#     - verify-ios
#     - verify-android
#     - verify-web
#   steps:
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 18.x
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: 0
#     - name: Restore Dependency Cache
#       id: cache-modules
#       uses: actions/cache@v2
#       with:
#         path: |
#           node_modules
#           */node_modules
#         key: dependency-cache-${{ hashFiles('package.json', '*/package.json') }}
#     - run: npm install
#     - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
#     - run: npx lerna publish from-git --yes
