name: Publish Native iOS Libraries

on:
  workflow_dispatch:
    inputs:
      plugins:
        description: 'Specify a set of plugins to publish (as a JSON array, ex: [\"camera\", \"browser\"])'
        required: true
jobs:
  publish-ios:
    runs-on: macos-14
    if: github.event.inputs.plugins != '[]'
    timeout-minutes: 30
    strategy:
      matrix:
        plugin: ${{ fromJson(github.event.inputs.plugins) }}
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_14.2.app
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 18.x
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: native-publish
      - name: Install Cocoapods
        run: |
          gem install cocoapods
      - name: Restore Dependency Cache
        id: cache-modules
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: |
            node_modules
            */node_modules
          key: dependency-cache-${{ hashFiles('package.json', '*/package.json') }}
      - run: yarn install
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          yarn run publish:cocoapod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
